namespace Velocitech.Utils.RustCodeGenerationTool.Renderizables.Variables.Numbers
{
    public enum NumericVariableTypeRender
    {
        NUMERIC_MUTABLE_VARIABLE_AS_VALUE,
        NUMERIC_MUTABLE_VARIABLE_AS_REFERENCE,
        NUMERIC_MUTABLE_VARIABLE_AS_MUTABLE_REFERENCE,        
        NUMERIC_INMUTABLE_VARIABLE_AS_VALUE,
        NUMERIC_INMUTABLE_VARIABLE_AS_REFERENCE,
        NUMERIC_INMUTABLE_VARIABLE_AS_MUTABLE_REFERENCE
    }
}
